# Generated by Django 3.2 on 2021-05-06 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Nouriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prix', models.FloatField()),
                ('image', models.ImageField(default='pexels-maarten-van-den-heuvel-2284166.jpg', upload_to='upload/image_nouriture/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Pannier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('nouriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.nouriture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(default='8 rue des flamboyant', max_length=500)),
                ('code_postale', models.CharField(default='97300', max_length=20)),
                ('ville', models.CharField(default='Cayenne', max_length=40)),
                ('date_debut', models.DateField(auto_now=True)),
                ('commander', models.BooleanField()),
                ('nouritures', models.ManyToManyField(to='restaurant.Pannier')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
