# Generated by Django 3.2 on 2021-05-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pannier',
            name='commander',
            field=models.BooleanField(default='False'),
        ),
    ]
